server:
  port: 8080

jwt:
  secretKey: ${JWT_SECRET}
  expiredMs: 3600000

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: operation
            uri: http://operation:8080
            predicates:
              - Path=/api/operation/**

          - id: vehicleaudit
            uri: http://vehicleaudit:8080
            predicates:
              - Path=/api/vehicleaudit/**

          - id: taskreports
            uri: http://taskreports:8080
            predicates:
              - Path=/api/taskreports/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  -  ${FRONT_DNS}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
    #           allowCredentials: true
