server:
  port: 8080

jwt:
  secretKey: Ag&h2NbdPUef#Ayuep@aif8klvSk!fsAdj3wnk&kaWnv#id0F
  expiredMs: 3600000

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: operation
            uri: http://localhost:8081
            predicates:
              - Path=/api/operation/**

          - id: vehicleaudit
            uri: http://localhost:8082
            predicates:
              - Path=/api/vehicleaudit/**

          - id: taskreports
            uri: http://localhost:8083
            predicates:
              - Path=/api/taskreports/**

          - id: frontend
            uri: http://localhost:5173
            predicates:
              - Path=/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173" # Ingress에서 실제 도메인으로 설정 권장
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
    #           allowCredentials: true
