server:
  port: 8080

jwt:
  secretKey: Ag&h2NbdPUef#Ayuep@aif8klvSk!fsAdj3wnk&kaWnv#id0F
  expiredMs: 3600000

spring:
  application:
    name: gateway

  cloud:
   gateway:
     server:
       webflux:
         routes:
           - id: admin
             uri: http://localhost:8081
             predicates:
               - Path=/api/operation/**,

           - id: frontend
             uri: http://localhost:3000
             predicates:
               - Path=/**
