server:
  port: 8080

jwt:
  secretKey: Ag&h2NbdPUef#Ayuep@aif8klvSk!fsAdj3wnk&kaWnv#id0F
  expiredMs: 3600000

spring:
  application:
    name: gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: admin
            uri: http://localhost:8081
            predicates:
              - Path=/api/operation/**

          - id: frontend
            uri: http://localhost:5173
            predicates:
              - Path=/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
#                allowCredentials: true
